### ISSUE TITLE
This plugin incorrecly pastes group contents

### ISSUE THREAD

**Issue by MondayPM** [dairin0d/cut-copy-paste#2]
This plugin creates impossible to delete contents of group's because it does not append the contents of groups into the scene, instead appending the group contents into the blend file without making theme selectable,deletable or modifyable. It should instead use the workflow of the append, where the contents of the group are placed into the scene, preferably at the same layers. 

The problems cause by this operation are detailed in this bug wherein the group and group contents accumulate recursive impossible to remove users making them impossible to remove the file:

https://developer.blender.org/T44890

**Comment by dairin0d** [comment]
Added option (enabled by default) to link "ghost" objects to current scene on pasting.
