### ISSUE TITLE
Incorrect pasting of objects with parent child transformations

### ISSUE THREAD

**Issue by MondayPM** [dairin0d/cut-copy-paste#3]
When pasting, objects that have a parent and are transformed against the parent's coordinate system are not pasted correctly. There is an offset occuring that doesn't replicated the correct positioning of the source objects.

**Comment by dairin0d** [comment]
I finally managed to get around to this bug. This seems to be a general problem when re-parenting, but re-assigning the global matrix apparently fixes the issue.
